---
version: '3'

volumes:
  test_gems:
  cargo_cache:

services:
  test:
    build:
      context: ./test
      dockerfile: dockerfiles/Dockerfile-test
    volumes:
      - ./:/sysunit
      - test_gems:/usr/local/bundle
      - cargo_cache:/usr/local/cargo
    environment:
      SYSUNIT_PATH: /sysunit/units
      GEM_HOME: /usr/local/bundle
    links:
      - ssh_host
    command: "sh -c 'cd test && bin/test-sysunit'"

  ssh_host:
    build:
      context: ./test/
      dockerfile: dockerfiles/Dockerfile-ssh_host
    command: /usr/sbin/sshd -D
